### -----AUTH-------
GET  http://62.84.117.214:9003/api/users/
Content-Type: application/json
###
POST http://62.84.117.214:9003/api/users/
Content-Type: application/json

{
    "email": "ee-3@ya.ru",
    "username": "q1",
    "first_name": "vi",
    "last_name": "pi",
    "password": "q1r4w2e3"
}
###
POST http://62.84.117.214:9003/api/api-token-auth/
Content-Type: application/json

{
    "username": "ee-2@ya.ru",
    "password": "Vitaliya"
}
###
GET http://62.84.117.214:9003/api/users/1/
Content-Type: application/json
Authorization: Token 4b5ea97d4784174cd1f8927ec193f39a31c916f9
###
GET http://62.84.117.214:9003/api/users/me/
Content-Type: application/json
Authorization: Token 4b5ea97d4784174cd1f8927ec193f39a31c916f9
###
POST http://62.84.117.214:9003/api/users/set_password/
Content-Type: application/json
Authorization: Token 4b5ea97d4784174cd1f8927ec193f39a31c916f9

{
    "new_password": "q1r4w2e3",
    "current_password": "q1r4w2e3"
}
###
POST http://62.84.117.214:9003/api/auth/token/login/
Content-Type: application/json

{
    "email": "ee-3@ya.ru",
    "password": "q1r4w2e3"
}
###
POST http://62.84.117.214:9003/api/auth/token/logout/
Content-Type: application/json
Authorization: Token 4b5ea97d4784174cd1f8927ec193f39a31c916f9

### -----TAGS-------
GET http://62.84.117.214:9003/api/tag/
Content-Type: application/json
###
GET http://62.84.117.214:9003/api/tag/2/
Content-Type: application/json

### -----INGREDIENTS-------
GET http://62.84.117.214:9003/api/ingredient/
Content-Type: application/json
###
GET http://62.84.117.214:9003/api/ingredient/1/
Content-Type: application/json

### -----RECIPES-------
GET http://62.84.117.214:9003/api/recipes/
Content-Type: application/json
